openapi: 3.0.1
info:
  title: xendit-opencart-module
  description: xendit-opencart-module
  x-cortex-git:
    github:
      repository: xendit/xendit-opencart-module
  x-cortex-tag: xendit-opencart-module
  x-cortex-owners:
  - type: GROUP
    name: xendit/tpi-dev
  - email: adhiarta@xendit.co
    type: EMAIL
  x-cortex-service-groups:
  - adhiarta@xendit.co
  - P2
  - TPI
